# Language Configuration

[en]
  title = ""
  description = "Docker Community"
  languageName = "English"
  contentDir = "content/en"
  # Weight used for sorting.
  weight = 1
  time_format_default = "01.01.2021"
  time_format_blog = "01.01.2021"
